# Window indexing from 1
set -g base-index 1

# Enable mouse
set -g mouse on

# Display session name on the left
set -g status-left "[#S] "
set -g status-right "%H:%M %d-%b-%y"

# Cursor display
set -g cursor-style blinking-block

set -g mode-keys vi
set -g status-keys vi

if-shell "uname | grep -q Darwin" {

	source-file .macos.tmux.conf
}

# === Plugins ===
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'


set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tmux-pain-control'


run '~/.tmux/plugins/tpm/tpm'
