# Prefix Ctrl+tilde [~]
set -g prefix C-w
unbind C-b
bind C-w send-prefix

# Window indexing from 1
set -g base-index 1

# Enable mouse
set -g mouse on

# Display session name on the left
set -g status-left "[#S] "
set -g status-right "%H:%M %d-%b-%y"

# Cursor display
set -g cursor-style blinking-bar

# === Plugins ===
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'


set -g @plugin 'rose-pine/tmux'



run '~/.tmux/plugins/tpm/tpm'


